# intro of torch

## basci of nn
we have input -> hidden layer -> ... -> hidden layer -> output, this is the basci architecture of fully connnected layer
for each neuron, all values from last layer come with $<W, b>$, $x_k = Wx_{k-1} + b, x_k \in \mathbb{R}^n, x_{k-1} \in \mathbb{R}^m$, will go through an active function
active function is probanly ReLU, Sigmoid

## basic of train process
we have big data, split the data into several batched, in each step, we input a batche of data, the networt computes, 
and the optimizor compute the gradient based on loss function and try to update params based on gradient optimazation controling the lr

the reason why we use GPU for network is that a small network has 3 million params, a regular network has 30 millions params
and the forward process is not a big deal, so we need to make a lot of "small" calculation
GPU is for image, which needs to do a lot of small calculation, thats why it would be more suitable than CPU

# we can consider torch as numpy on GPU, which has more functions
the main difference is we can run tensor on GPU

In [1]:
import torch

In [2]:
x = torch.Tensor([3, 5])
y = torch.Tensor([2, 1])

In [3]:
x * y

tensor([6., 5.])

In [4]:
# in torch, we use list as dim, not params
x = torch.zeros([2, 5])
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [5]:
x.shape

torch.Size([2, 5])

In [7]:
y = torch.randn([2, 5])
y

tensor([[ 1.7311, -0.5477, -0.3561, -0.8304,  0.4026],
        [ 0.8274, -1.2331, -0.1192,  0.0193,  0.9395]])

In [9]:
# reshape
# in torch, we use .view not .reshape as in numpy 
y.view([1, 10])

tensor([[ 1.7311, -0.5477, -0.3561, -0.8304,  0.4026,  0.8274, -1.2331, -0.1192,
          0.0193,  0.9395]])

In [10]:
# not inplace
y

tensor([[ 1.7311, -0.5477, -0.3561, -0.8304,  0.4026],
        [ 0.8274, -1.2331, -0.1192,  0.0193,  0.9395]])